# basics
set -g default-terminal "screen-256color"
set -g prefix C-a
set -sg escape-time 0

# let's free the original prefix
unbind C-b

# make sure we can send prefix to other apps
bind C-a send-prefix

# set pane and window index starts to 1
set -g base-index 1
setw -g pane-base-index 1

# set status bar to top
set-option -g status-position top

# Sessions
unbind s
unbind \;
bind \; choose-session

# Windows
unbind w
unbind "'"
bind "'" choose-window
bind a last-window

# Splits
unbind %
bind | split-window -h
bind - split-window -v

# Moving between panes
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# history
set -g history-limit 8192

