source = ~/.config/hypr/theme/macchiato.conf

$font-default = JetBrainsMono Nerd Font Mono
$font-bold-italic = JetBrainsMono Nerd Font Mono Bold Italic

general {
    hide_cursor = true
}

background {
    path = ~/Pictures/wukong.jpg
    blur_passes = 0
    brightness = 0.85
}

input-field {
    size = 15%, 5%
    outline_thickness = 2

    inner_color = $surface0_rgba
    outer_color = $overlay1_rgba

    check_color = $green_rgba
    fail_color = $red_rgba

    font_color = $text_rgba
    fade_on_empty = false

    rounding = 6

    font_family = $font-default
    placeholder_text = Password

    position = 0, -180
    halign = center
    valign = center
}

# Clock
label {
    text = cmd[update:1000] echo "$(date +"%-I:%M%p")"
    color = $lavender_rgba
    font_size = 90
    font_family = $font-default

    position = 0, 180
    halign = center
    valign = center
}

# User label
label {
    text = $USER
    color = $subtext1_rgba
    font_size = 16
    font_family = $font-bold-italic

    position = 0, 30
    halign = center
    valign = bottom
}

# Layout switcher
label {
    text = <b>$LAYOUT[en,uk]</b>
    color = $blue_rgba
    font_family = $font-default

    position = 180, -180
    halign = center
    valign = center

    onclick = hyprctl switchxkblayout all next
}
